version: '3.8'
# docker-compose
services:
  sinloingok-app:
    network_mode: "host"
    container_name: sinloingok-container
    build:
      context: .
      dockerfile: Dockerfile
    image: sinloingok-app:latest
    volumes:
      - /opt/apache-tomcat-8.5.78/cert:/sinloingok/cert
      - ./logs:/sinloingok/logs
    environment:
      - TZ=Asia/Shanghai
      - SPRING_PROFILES_ACTIVE=prd
