spring:
  datasource:
#    url: jdbc:mysql://47.94.103.164:3306/info?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: whisper
#    password: wsj2875511
    url: jdbc:mysql://localhost:3306/sinloingok?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 显示 SQL 到控制台

sinloingok:
  wechat:
    notifyUrlRecharge: "http://t9337e6d.natappfree.cc/payment/sbpaycallForRecharge"

# Netty服务器自定义配置
netty:
  server:
    port: 18080 # Netty服务器监听端口
    host: 0.0.0.0 # 绑定地址，0.0.0.0表示所有网络接口
    boss-threads: 1 # Boss线程组线程数，通常1个足够
    worker-threads: 0 # Worker线程组线程数，0表示使用Netty默认值(CPU核心数*2)
    so-backlog: 512 # 等待连接队列大小
    so-keepalive: true # 是否启用TCP KeepAlive
    idle:
      read-seconds: 30
      write-seconds: 10
    timeout:
      read-seconds: 20
      write-seconds: 10
    enable-traffic-shaping: false
    traffic:
      write-bytes-per-sec: 16777216
      read-bytes-per-sec: 16777216


logging:
  level:
    root: INFO
    org.springframework.web: INFO          # Spring MVC日志
    org.hibernate.SQL: DEBUG               # Hibernate SQL日志
    com.sinloingok.app: INFO               # 项目包日志
    org.springframework.scheduling: INFO
  file:
    name: logs/app.log                     # 输出到文件
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"