#ALIOSS ABOUT
ALIOSS_ENDPOINT = oss-cn-beijing.aliyuncs.com

ALIOSS_ACCESS_KEY_ID = LTAI5tFirsbnSJCDc3znutt5

ALIOSS_ACCESS_KEY_SECRET = RoY9hW8xA6yXxVhc0AraAeeNdOS0x0

ALIOSS_BUCKET_NAM = dsosm

#ALIPAY ABOUT
ALIPAY_APP_ID = 

ALIPAY_PRIVATE_KEY = 

ALIPAY_PUBLIC_KEY = 

ZHIFUBAO_PUBLIC_KEY = 

ALIPAY_CHARSET = utf-8

ALIPAY_SIGNTYPE = RSA2

ALIPAY_URL = https://openapi.alipay.com/gateway.do

ALIPAY_FORMAT = json

BASE_URL = 

#WXAPPPAY ABOUT
WEIXIN_APP_PAY_APPID = wx5e846373168be490
#gaowei
WEIXIN_APP_PAY_MCHID = 1642124235
# guowenchao
#WEIXIN_APP_PAY_MCHID = 1717262533


WEIXIN_APP_PAY_PRIVATE_KEY = b8q8nARUoXvIPg7vJJidHdUaPffQ8fEZ

#shengchan huanjing
WEIXIN_APP_PAY_NOTIFY_URL_RECHARGE = https://acc.dakakj.com/payment/sbpaycallForRecharge
# test guowenchao
#WEIXIN_APP_PAY_NOTIFY_URL_RECHARGE = http://f829833e.natappfree.cc/payment/sbpaycallForRecharge
#收錢吧 shouqianba
#WEIXIN_APP_PAY_NOTIFY_URL_RECHARGE = http://h7a23643.natappfree.cc/payment/sbpaycallForRecharge
#WEIXIN_APP_PAY_NOTIFY_URL_COUPONPAY = http://47.94.103.164/ACCCheJieHuiApp/pay/wxpaycallForCouponPay

WEIXIN_APP_PAY_NOTIFY_URL_LOCKPAY = http://47.94.103.164/ACCCheJieHuiApp/pay/wxpaycallForLockPay

WEIXIN_APP_PAY_NOTIFY_URL_AUTOCLEAN = http://47.94.103.164/ACCCheJieHuiApp/pay/wxpaycallForAutoCleanPay

#
#WEIXIN_APPID = wx5e846373168be490
#WEIXIN_APPSECRET = 1e8d9d7e6a73d9022e978b166d64c041
#WEIXIN_PRIVATE_KEY = b8q8nARUoXvIPg7vJJidHdUaPffQ8fEZ
#gaowei
#WEIXIN_MCHID = 1642124235
# wangjie
#WEIXIN_MCHID = 1684677433
# guowenchao
#WEIXIN_MCHID = 1717262533


WEIXIN_APPID = wx5e846373168be490
WEIXIN_APPSECRET = 1e8d9d7e6a73d9022e978b166d64c041
WEIXIN_PRIVATE_KEY = b8q8nARUoXvIPg7vJJidHdUaPffQ8fEZ
WEIXIN_MCHID = 1642124235


# sinloingok config
#WEIXIN_APPID = wx6a42e490c14731a7
#WEIXIN_APPSECRET = a3a62fb864e27a77bc5aae88684daae4
#WEIXIN_PRIVATE_KEY = b8q8nARUoXvIPg7vJJidHdUaPffQ8fEZ
#WEIXIN_MCHID = 1717262533


