INSERT INTO district(code,name,value,description) VALUES ('ResultCodeSUCCESS','SUCCESS','000','');
INSERT INTO district(code,name,value,description) VALUES ('ResultCodeERROR','ERROR','999','');
INSERT INTO district(code,name,value,description) VALUES ('PayTypealipay','alipay','支付宝','');
INSERT INTO district(code,name,value,description) VALUES ('PayTypewechat','wechat','微信','');
INSERT INTO district(code,name,value,description) VALUES ('SystemConstantCOMMON_CODE','COMMON_CODE','YUANYUANGODDESS','系统常量  生成Token的公用码');
INSERT INTO district(code,name,value,description) VALUES ('SystemConstantAVATAR_BASE','AVATAR_BASE','/uploads/avatar','系统常量  头像上传位置');
INSERT INTO district(code,name,value,description) VALUES ('SystemConstantDEFAULT_AVATAR','DEFAULT_AVATAR','/uploads/imgs/default/avatar.jpg','系统常量  默认头像');
INSERT INTO district(code,name,value,description) VALUES ('DateFormatFORMAT','FORMAT','yyyy-MM-dd HH:mm:ss','');
INSERT INTO district(code,name,value,description) VALUES ('UserStatusNORMAL','NORMAL','正常','');
INSERT INTO district(code,name,value,description) VALUES ('UserStatusDELETED','DELETED','删除','');
INSERT INTO district(code,name,value,description) VALUES ('UserMoneyRecordTypeCANCEL','CANCEL','取消订单','');
INSERT INTO district(code,name,value,description) VALUES ('UserMoneyRecordTypeCONSUME','CONSUME','消费','');
INSERT INTO district(code,name,value,description) VALUES ('UserMoneyRecordTypeRECHARGE','RECHARGE','充值','');
INSERT INTO district(code,name,value,description) VALUES ('UserMoneyRecordTypeREFUND','REFUND','退款','');
INSERT INTO district(code,name,value,description) VALUES ('UserMoneyRecordTypeSPREAD_AWARDS','SPREAD_AWARDS','推荐有奖','');
INSERT INTO district(code,name,value,description) VALUES ('UserMoneyRecordTypeWITHDRAW','WITHDRAW','提现','');
INSERT INTO district(code,name,value,description) VALUES ('UserMoneyRecordTypeRECHARGE_GIVE','RECHARGE_GIVE','充值赠送','');
INSERT INTO district(code,name,value,description) VALUES ('UserMoneyRecordTypeBACK_EDIT','BACK_EDIT','管理修改','');
INSERT INTO district(code,name,value,description) VALUES ('RoleIDSUPEERADMIN','SUPEERADMIN','32','用户角色ID  超级管理员角色ID');
INSERT INTO district(code,name,value,description) VALUES ('RoleIDMEMBER','MEMBER','33','用户角色ID  会员角色ID');
INSERT INTO district(code,name,value,description) VALUES ('RoleIDSELLER','SELLER','34','用户角色ID  加盟商角色ID');
INSERT INTO district(code,name,value,description) VALUES ('RoleIDDAILI','DAILI','68','用户角色ID  代理角色ID');
INSERT INTO district(code,name,value,description) VALUES ('RoleIDSHANGHU','SHANGHU','70','用户角色ID  商户角色ID');
INSERT INTO district(code,name,value,description) VALUES ('SpreadAwardsApplyStatusAPPLY','APPLY','申请中','');
INSERT INTO district(code,name,value,description) VALUES ('SpreadAwardsApplyStatusFINISHED','FINISHED','已完成','');
INSERT INTO district(code,name,value,description) VALUES ('UserLevelNORMAL','NORMAL','普通会员','');
INSERT INTO district(code,name,value,description) VALUES ('ManageUserStatusUSING','USING','启用','');
INSERT INTO district(code,name,value,description) VALUES ('ManageUserStatusNO_USING','NO_USING','暂不启用','');
INSERT INTO district(code,name,value,description) VALUES ('ManageUserStatusAPPLY','APPLY','申请中','');
INSERT INTO district(code,name,value,description) VALUES ('ManageUserStatusFAIL','FAIL','拒绝','');
INSERT INTO district(code,name,value,description) VALUES ('LoginFlagLOGINING','LOGINING','登录中','');
INSERT INTO district(code,name,value,description) VALUES ('LoginFlagLOGOUT','LOGOUT','退出登录','');
INSERT INTO district(code,name,value,description) VALUES ('CategoryStatusNORMAL','NORMAL','正常','');
INSERT INTO district(code,name,value,description) VALUES ('CategoryStatusDELETE','DELETE','删除','');
INSERT INTO district(code,name,value,description) VALUES ('CalcStatusNO_CALC','NO_CALC','未结算','');
INSERT INTO district(code,name,value,description) VALUES ('CalcStatusIS_CALA','IS_CALA','结算申请中','');
INSERT INTO district(code,name,value,description) VALUES ('CalcStatusCALCED','CALCED','已结算','');
INSERT INTO district(code,name,value,description) VALUES ('BluetoothAddressStatusNORMAL','NORMAL','正常','');
INSERT INTO district(code,name,value,description) VALUES ('BluetoothAddressStatusDELETE','DELETE','删除','');
INSERT INTO district(code,name,value,description) VALUES ('OrderStatusPAY_WAITTING','PAY_WAITTING','待付款','');
INSERT INTO district(code,name,value,description) VALUES ('OrderStatusACCEPT_WAITTING','ACCEPT_WAITTING','待发货','');
INSERT INTO district(code,name,value,description) VALUES ('OrderStatusRECEIVE_WAITTING','RECEIVE_WAITTING','待收货','');
INSERT INTO district(code,name,value,description) VALUES ('OrderStatusFINISHED','FINISHED','已完成','');
INSERT INTO district(code,name,value,description) VALUES ('OrderStatusCANCELED','CANCELED','已取消','');
INSERT INTO district(code,name,value,description) VALUES ('OrderStatusDELETED','DELETED','已删除','');
INSERT INTO district(code,name,value,description) VALUES ('OrderStatusUSEING','USEING','使用中','');
INSERT INTO district(code,name,value,description) VALUES ('OrderStatusSUSPEND','SUSPEND','暂停中','');
INSERT INTO district(code,name,value,description) VALUES ('NetOrderCloseStatusWAITING','WAITING','等待中','');
INSERT INTO district(code,name,value,description) VALUES ('NetOrderCloseStatusCLSED','CLSED','已关闭','');
INSERT INTO district(code,name,value,description) VALUES ('NetSiteStatusONLINE','ONLINE','在线','');
INSERT INTO district(code,name,value,description) VALUES ('NetSiteStatusOFFLINE','OFFLINE','离线','');
INSERT INTO district(code,name,value,description) VALUES ('NetSiteStatusDELETE','DELETE','删除','');
INSERT INTO district(code,name,value,description) VALUES ('NetSiteStatusUSED','USED','使用中','');
INSERT INTO district(code,name,value,description) VALUES ('AddressStatusNORMAL','NORMAL','一般','');
INSERT INTO district(code,name,value,description) VALUES ('AddressStatusDEFAULT','DEFAULT','默认','');
INSERT INTO district(code,name,value,description) VALUES ('AddressStatusDELETED','DELETED','已删除','');